name: Test
description: Testing 1.2.3
body:
  - type: markdown
    attributes:
      value: |
        **Hello World**
  - type: input
    id: version
    attributes:
      label: Some Label
      description: Hello
